/**:
  ros__parameters:

    configuration:
      cap_width: 640 #1280
      cap_height: 480  #720
      frame_id: "camera_link"
      camera_name: "raspicam"
      display_width: 640
      display_height: 480
      framerate: 30.0
      # 0=reverse, 2=normal
      flip_mode: 0 
      # camera_calibration_file: "package://rastreator_camera/config/picam_calibration.yaml"
        

